import { Pokemon } from './pokemon';
export const POKEMON: Pokemon[] = [
    { pokemonid: 1, name: 'bulbasaur', types: ['grass', 'poison'] },
    { pokemonid: 2, name: 'ivysaur', types: ['grass', 'poison'] },
    { pokemonid: 3, name: 'venusaur', types: ['grass', 'poison'] },
    { pokemonid: 4, name: 'charmander', types: ['fire'] },
    { pokemonid: 5, name: 'charmeleon', types: ['fire'] },
    { pokemonid: 6, name: 'charizard', types: ['fire', 'flying'] },
    { pokemonid: 7, name: 'squirtle', types: ['water'] },
    { pokemonid: 8, name: 'wartortle', types: ['water'] },
    { pokemonid: 9, name: 'blastoise', types: ['water'] },
    { pokemonid: 10, name: 'caterpie', types: ['bug'] },
    { pokemonid: 11, name: 'metapod', types: ['bug'] },
    { pokemonid: 12, name: 'butterfree', types: ['bug', 'flying'] },
    { pokemonid: 13, name: 'weedle', types: ['bug', 'poison'] },
    { pokemonid: 14, name: 'kakuna', types: ['bug', 'poison'] },
    { pokemonid: 15, name: 'beedrill', types: ['bug', 'poison'] },
    { pokemonid: 16, name: 'pidgey', types: ['normal', 'flying'] },
    { pokemonid: 17, name: 'pidgeotto', types: ['normal', 'flying'] },
    { pokemonid: 18, name: 'pidgeot', types: ['normal', 'flying'] },
    { pokemonid: 19, name: 'rattata', types: ['normal'] },
    { pokemonid: 20, name: 'raticate', types: ['normal'] },
    { pokemonid: 21, name: 'spearow', types: ['normal', 'flying'] },
    { pokemonid: 22, name: 'fearow', types: ['normal', 'flying'] },
    { pokemonid: 23, name: 'ekans', types: ['poison'] },
    { pokemonid: 24, name: 'arbok', types: ['poison'] },
    { pokemonid: 25, name: 'pikachu', types: ['electric'] },
    { pokemonid: 26, name: 'raichu', types: ['electric'] },
    { pokemonid: 30, name: 'nidorina', types: ['poison'] },
    { pokemonid: 31, name: 'nidoqueen', types: ['poison', 'ground'] },
    { pokemonid: 33, name: 'nidorino', types: ['poison'] },
    { pokemonid: 34, name: 'nidoking', types: ['poison', 'ground'] },
    { pokemonid: 35, name: 'clefairy', types: ['fairy'] },
    { pokemonid: 36, name: 'clefable', types: ['fairy'] },
    { pokemonid: 37, name: 'vulpix', types: ['fire'] },
    { pokemonid: 38, name: 'ninetales', types: ['fire'] },
    { pokemonid: 39, name: 'jigglypuff', types: ['normal', 'fairy'] },
    { pokemonid: 40, name: 'wigglytuff', types: ['normal', 'fairy'] },
    { pokemonid: 41, name: 'zubat', types: ['poison', 'flying'] },
    { pokemonid: 42, name: 'golbat', types: ['poison', 'flying'] },
    { pokemonid: 43, name: 'oddish', types: ['grass', 'poison'] },
    { pokemonid: 44, name: 'gloom', types: ['grass', 'poison'] },
    { pokemonid: 45, name: 'vileplume', types: ['grass', 'poison'] },
    { pokemonid: 46, name: 'paras', types: ['bug', 'grass'] },
    { pokemonid: 47, name: 'parasect', types: ['bug', 'grass'] },
    { pokemonid: 27, name: 'sandshrew', types: ['ground'] },
    { pokemonid: 28, name: 'sandslash', types: ['ground'] },
    { pokemonid: 48, name: 'venonat', types: ['bug', 'poison'] },
    { pokemonid: 49, name: 'venomoth', types: ['bug', 'poison'] },
    { pokemonid: 50, name: 'diglett', types: ['ground'] },
    { pokemonid: 51, name: 'dugtrio', types: ['ground'] },
    { pokemonid: 52, name: 'meowth', types: ['normal'] },
    { pokemonid: 56, name: 'mankey', types: ['fighting'] },
    { pokemonid: 57, name: 'primeape', types: ['fighting'] },
    { pokemonid: 58, name: 'growlithe', types: ['fire'] },
    { pokemonid: 59, name: 'arcanine', types: ['fire'] },
    { pokemonid: 60, name: 'poliwag', types: ['water'] },
    { pokemonid: 61, name: 'poliwhirl', types: ['water'] },
    { pokemonid: 62, name: 'poliwrath', types: ['water', 'fighting'] },
    { pokemonid: 63, name: 'abra', types: ['psychic'] },
    { pokemonid: 64, name: 'kadabra', types: ['psychic'] },
    { pokemonid: 65, name: 'alakazam', types: ['psychic'] },
    { pokemonid: 66, name: 'machop', types: ['fighting'] },
    { pokemonid: 67, name: 'machoke', types: ['fighting'] },
    { pokemonid: 68, name: 'machamp', types: ['fighting'] },
    { pokemonid: 69, name: 'bellsprout', types: ['grass', 'poison'] },
    { pokemonid: 70, name: 'weepinbell', types: ['grass', 'poison'] },
    { pokemonid: 71, name: 'victreebel', types: ['grass', 'poison'] },
    { pokemonid: 72, name: 'tentacool', types: ['water', 'poison'] },
    { pokemonid: 73, name: 'tentacruel', types: ['water', 'poison'] },
    { pokemonid: 53, name: 'persian', types: ['normal'] },
    { pokemonid: 54, name: 'psyduck', types: ['water'] },
    { pokemonid: 55, name: 'golduck', types: ['water'] },
    { pokemonid: 74, name: 'geodude', types: ['rock', 'ground'] },
    { pokemonid: 75, name: 'graveler', types: ['rock', 'ground'] },
    { pokemonid: 76, name: 'golem', types: ['rock', 'ground'] },
    { pokemonid: 77, name: 'ponyta', types: ['fire'] },
    { pokemonid: 78, name: 'rapidash', types: ['fire'] },
    { pokemonid: 82, name: 'magneton', types: ['electric', 'steel'] },
    { pokemonid: 84, name: 'doduo', types: ['normal', 'flying'] },
    { pokemonid: 85, name: 'dodrio', types: ['normal', 'flying'] },
    { pokemonid: 86, name: 'seel', types: ['water'] },
    { pokemonid: 87, name: 'dewgong', types: ['water', 'ice'] },
    { pokemonid: 88, name: 'grimer', types: ['poison'] },
    { pokemonid: 89, name: 'muk', types: ['poison'] },
    { pokemonid: 90, name: 'shellder', types: ['water'] },
    { pokemonid: 91, name: 'cloyster', types: ['water', 'ice'] },
    { pokemonid: 92, name: 'gastly', types: ['ghost', 'poison'] },
    { pokemonid: 93, name: 'haunter', types: ['ghost', 'poison'] },
    { pokemonid: 94, name: 'gengar', types: ['ghost', 'poison'] },
    { pokemonid: 95, name: 'onix', types: ['rock', 'ground'] },
    { pokemonid: 96, name: 'drowzee', types: ['psychic'] },
    { pokemonid: 97, name: 'hypno', types: ['psychic'] },
    { pokemonid: 98, name: 'krabby', types: ['water'] },
    { pokemonid: 99, name: 'kingler', types: ['water'] },
    { pokemonid: 79, name: 'slowpoke', types: ['water', 'psychic'] },
    { pokemonid: 80, name: 'slowbro', types: ['water', 'psychic'] },
    { pokemonid: 81, name: 'magnemite', types: ['electric', 'steel'] },
    { pokemonid: 100, name: 'voltorb', types: ['electric'] },
    { pokemonid: 101, name: 'electrode', types: ['electric'] },
    { pokemonid: 102, name: 'exeggcute', types: ['grass', 'psychic'] },
    { pokemonid: 103, name: 'exeggutor', types: ['grass', 'psychic'] }
];
