import { Pokemon } from './pokemon';
export const POKEMON: Pokemon[] = [
    { _id: 1, name: 'bulbasaur', types: ['grass', 'poison'] },
    { _id: 2, name: 'ivysaur', types: ['grass', 'poison'] },
    { _id: 3, name: 'venusaur', types: ['grass', 'poison'] },
    { _id: 4, name: 'charmander', types: ['fire'] },
    { _id: 5, name: 'charmeleon', types: ['fire'] },
    { _id: 6, name: 'charizard', types: ['fire', 'flying'] },
    { _id: 7, name: 'squirtle', types: ['water'] },
    { _id: 8, name: 'wartortle', types: ['water'] },
    { _id: 9, name: 'blastoise', types: ['water'] },
    { _id: 10, name: 'caterpie', types: ['bug'] },
    { _id: 11, name: 'metapod', types: ['bug'] },
    { _id: 12, name: 'butterfree', types: ['bug', 'flying'] },
    { _id: 13, name: 'weedle', types: ['bug', 'poison'] },
    { _id: 14, name: 'kakuna', types: ['bug', 'poison'] },
    { _id: 15, name: 'beedrill', types: ['bug', 'poison'] },
    { _id: 16, name: 'pidgey', types: ['normal', 'flying'] },
    { _id: 17, name: 'pidgeotto', types: ['normal', 'flying'] },
    { _id: 18, name: 'pidgeot', types: ['normal', 'flying'] },
    { _id: 19, name: 'rattata', types: ['normal'] },
    { _id: 20, name: 'raticate', types: ['normal'] },
    { _id: 21, name: 'spearow', types: ['normal', 'flying'] },
    { _id: 22, name: 'fearow', types: ['normal', 'flying'] },
    { _id: 23, name: 'ekans', types: ['poison'] },
    { _id: 24, name: 'arbok', types: ['poison'] },
    { _id: 25, name: 'pikachu', types: ['electric'] },
    { _id: 26, name: 'raichu', types: ['electric'] },
    { _id: 30, name: 'nidorina', types: ['poison'] },
    { _id: 31, name: 'nidoqueen', types: ['poison', 'ground'] },
    { _id: 33, name: 'nidorino', types: ['poison'] },
    { _id: 34, name: 'nidoking', types: ['poison', 'ground'] },
    { _id: 35, name: 'clefairy', types: ['fairy'] },
    { _id: 36, name: 'clefable', types: ['fairy'] },
    { _id: 37, name: 'vulpix', types: ['fire'] },
    { _id: 38, name: 'ninetales', types: ['fire'] },
    { _id: 39, name: 'jigglypuff', types: ['normal', 'fairy'] },
    { _id: 40, name: 'wigglytuff', types: ['normal', 'fairy'] },
    { _id: 41, name: 'zubat', types: ['poison', 'flying'] },
    { _id: 42, name: 'golbat', types: ['poison', 'flying'] },
    { _id: 43, name: 'oddish', types: ['grass', 'poison'] },
    { _id: 44, name: 'gloom', types: ['grass', 'poison'] },
    { _id: 45, name: 'vileplume', types: ['grass', 'poison'] },
    { _id: 46, name: 'paras', types: ['bug', 'grass'] },
    { _id: 47, name: 'parasect', types: ['bug', 'grass'] },
    { _id: 27, name: 'sandshrew', types: ['ground'] },
    { _id: 28, name: 'sandslash', types: ['ground'] },
    { _id: 48, name: 'venonat', types: ['bug', 'poison'] },
    { _id: 49, name: 'venomoth', types: ['bug', 'poison'] },
    { _id: 50, name: 'diglett', types: ['ground'] },
    { _id: 51, name: 'dugtrio', types: ['ground'] },
    { _id: 52, name: 'meowth', types: ['normal'] },
    { _id: 56, name: 'mankey', types: ['fighting'] },
    { _id: 57, name: 'primeape', types: ['fighting'] },
    { _id: 58, name: 'growlithe', types: ['fire'] },
    { _id: 59, name: 'arcanine', types: ['fire'] },
    { _id: 60, name: 'poliwag', types: ['water'] },
    { _id: 61, name: 'poliwhirl', types: ['water'] },
    { _id: 62, name: 'poliwrath', types: ['water', 'fighting'] },
    { _id: 63, name: 'abra', types: ['psychic'] },
    { _id: 64, name: 'kadabra', types: ['psychic'] },
    { _id: 65, name: 'alakazam', types: ['psychic'] },
    { _id: 66, name: 'machop', types: ['fighting'] },
    { _id: 67, name: 'machoke', types: ['fighting'] },
    { _id: 68, name: 'machamp', types: ['fighting'] },
    { _id: 69, name: 'bellsprout', types: ['grass', 'poison'] },
    { _id: 70, name: 'weepinbell', types: ['grass', 'poison'] },
    { _id: 71, name: 'victreebel', types: ['grass', 'poison'] },
    { _id: 72, name: 'tentacool', types: ['water', 'poison'] },
    { _id: 73, name: 'tentacruel', types: ['water', 'poison'] },
    { _id: 53, name: 'persian', types: ['normal'] },
    { _id: 54, name: 'psyduck', types: ['water'] },
    { _id: 55, name: 'golduck', types: ['water'] },
    { _id: 74, name: 'geodude', types: ['rock', 'ground'] },
    { _id: 75, name: 'graveler', types: ['rock', 'ground'] },
    { _id: 76, name: 'golem', types: ['rock', 'ground'] },
    { _id: 77, name: 'ponyta', types: ['fire'] },
    { _id: 78, name: 'rapidash', types: ['fire'] },
    { _id: 82, name: 'magneton', types: ['electric', 'steel'] },
    { _id: 84, name: 'doduo', types: ['normal', 'flying'] },
    { _id: 85, name: 'dodrio', types: ['normal', 'flying'] },
    { _id: 86, name: 'seel', types: ['water'] },
    { _id: 87, name: 'dewgong', types: ['water', 'ice'] },
    { _id: 88, name: 'grimer', types: ['poison'] },
    { _id: 89, name: 'muk', types: ['poison'] },
    { _id: 90, name: 'shellder', types: ['water'] },
    { _id: 91, name: 'cloyster', types: ['water', 'ice'] },
    { _id: 92, name: 'gastly', types: ['ghost', 'poison'] },
    { _id: 93, name: 'haunter', types: ['ghost', 'poison'] },
    { _id: 94, name: 'gengar', types: ['ghost', 'poison'] },
    { _id: 95, name: 'onix', types: ['rock', 'ground'] },
    { _id: 96, name: 'drowzee', types: ['psychic'] },
    { _id: 97, name: 'hypno', types: ['psychic'] },
    { _id: 98, name: 'krabby', types: ['water'] },
    { _id: 99, name: 'kingler', types: ['water'] },
    { _id: 79, name: 'slowpoke', types: ['water', 'psychic'] },
    { _id: 80, name: 'slowbro', types: ['water', 'psychic'] },
    { _id: 81, name: 'magnemite', types: ['electric', 'steel'] },
    { _id: 100, name: 'voltorb', types: ['electric'] },
    { _id: 101, name: 'electrode', types: ['electric'] },
    { _id: 102, name: 'exeggcute', types: ['grass', 'psychic'] },
    { _id: 103, name: 'exeggutor', types: ['grass', 'psychic'] }
];
