#!/usr/bin/env bash
workingdirectory="/tmp"
LINK="$1"

exitWithError() {
    local red='\e[31m'
    local end='\e[0m'
    echo -e "${red}==>    ERROR: $1${end}" >&2
    exit 2
}

if [[ ! -d $workingdirectory || ! -w $workingdirectory ]]; then
    exitWithError "Either ${workingdirectory} doesn't exists or is not writable"
fi

if [[ -z $LINK ]]; then
    exitWithError "Please provide a link"
fi

tarball="$(echo "$LINK" | awk -F/ '{print $(NF)}')"
tarballFile="${workingdirectory}/$tarball"
package=$(echo "$tarball" | cut -d'.' -f1)

if [[ -d ${workingdirectory}/$package ]]; then
    echo "Removing old ${workingdirectory}/$package"
    rm -rf "${workingdirectory:?}/$package"
fi

if [[ ! -f $tarballFile ]]; then
    echo "Downloading $tarballFile"
    if ! wget -P ${workingdirectory} "$LINK"; then
        exitWithError "Downloading $tarballFile"
    fi
fi

if ! tar -C ${workingdirectory} -xf "$tarballFile"; then
    exitWithError "untaring $tarballFile"
fi

cd "${workingdirectory}/$package" || exit 2
if ! makepkg -fcis; then
    exitWithError "creating package failed"
fi

exit 0
